---
- name: "Processing project {{ item_project.name }}"
  os_project:
    cloud: "{{ item_cloud.oscc_cloud|default(item_cloud.name) }}"
    state: "{{ item_project.state|default(omit) }}"
    name: "{{ item_project.name }}"
    description: "{{ item_project.description|default(omit) }}"
    domain: "{{ item_project.domain|default(omit) }}"
    region_name: "{{ item_cloud.region_name|default(omit) }}"
    validate_certs: "{{ os_validate_certs }}"
