---
- os_keypair:
    cloud: "{{ item_cloud.oscc_cloud|default(item_cloud.name) }}"
    state: "{{ item_keypair.state|default(omit) }}"
    name: "{{ item_keypair.name }}"
    public_key: "{{ item_keypair.public_key|default(omit) }}"
    public_key_file: "{{ item_keypair.public_key_file|default(omit) }}"
    region_name: "{{ item|default(omit) }}"
  with_items: "{{ item_cloud.regions|default(None) }}"
