---
- name: "Processing per cloud domains"
  include: create_domain.yml
  with_items: "{{ item_cloud.domains|default([]) }}"
  loop_control:
    loop_var: item_domain
  tags:
    - domains

- name: "Processing per cloud projects"
  include: create_project.yml
  with_items: "{{ item_cloud.projects|default([]) }}"
  loop_control:
    loop_var: item_project
  tags:
    - projects

- name: "Processing per cloud users"
  include: create_user.yml
  with_items: "{{ item_cloud.users|default([]) }}"
  loop_control:
    loop_var: item_user
  tags:
    - users

- name: "Processing per cloud networks"
  include: create_network.yml
  with_items: "{{ item_cloud.networks|default([]) }}"
  loop_control:
    loop_var: item_network
  tags:
    - networks

- name: "Processing per cloud subnets"
  include: create_subnet.yml
  with_items: "{{ item_cloud.subnets|default([]) }}"
  loop_control:
    loop_var: item_subnet
  tags:
    - subnets

- name: "Processing per cloud routers"
  include: create_router.yml
  with_items: "{{ item_cloud.routers|default([]) }}"
  loop_control:
    loop_var: item_router
  tags:
    - routers

- name: "Processing per cloud flavors"
  include: create_flavor.yml
  with_items: "{{ item_cloud.flavors|default([]) }}"
  loop_control:
    loop_var: item_flavor
  tags:
    - flavors

- name: "Processing per cloud images"
  include: create_image.yml
  with_items: "{{ item_cloud.images|default([]) }}"
  loop_control:
    loop_var: item_image
  tags:
    - images

- name: "Processing per cloud security_groups"
  include: create_security_group.yml
  with_items: "{{ item_cloud.security_groups|default([]) }}"
  loop_control:
    loop_var: item_security_group
  tags:
    - security_groups

- name: "Processing per cloud security_group_rules"
  include: create_security_group_rule.yml
  with_items: "{{ item_cloud.security_groups_rules|default([]) }}"
  loop_control:
    loop_var: item_security_group_rule
  tags:
    - security_groups_rules

- name: "Processing per cloud keypairs"
  include: create_keypair.yml
  with_items: "{{ item_cloud.keypairs|default([]) }}"
  loop_control:
    loop_var: item_keypair
  tags:
    - keypairs

- name: "Processing per cloud volumes"
  include: create_volume.yml
  with_items: "{{ item_cloud.volumes|default([]) }}"
  loop_control:
    loop_var: item_volume
  tags:
    - volumes

- name: "Processing per cloud servers"
  include: create_server.yml
  with_items: "{{ item_cloud.servers|default([]) }}"
  loop_control:
    loop_var: item_server
  tags:
    - servers
