---
- name: "Processing flavor {{ item_flavor.name }}"
  os_nova_flavor:
    cloud: "{{ item_cloud.oscc_cloud|default(item_cloud.name) }}"
    state: "{{ item_flavor.state|default(omit) }}"
    name: "{{ item_flavor.name }}"
    vcpus: "{{ item_flavor.vcpus }}"
    ram: "{{ item_flavor.ram }}"
    disk: "{{ item_flavor.disk }}"
    is_public: "{{ item_flavor.is_public|default(omit) }}"
    swap: "{{ item_flavor.swap|default(omit) }}"
    ephemeral: "{{ item_flavor.ephemeral|default(omit) }}"
    rxtx_factor: "{{ item_flavor.rxtx_factor|default(omit) }}"
    region_name: "{{ item_cloud.region_name|default(omit) }}"
    extra_specs: "{{ item_flavor.extra_specs|default(omit) }}"
