---
- os_router:
    validate_certs: "{{ item_cloud.validate_certs|default(omit) }}"
    cloud: "{{ item_cloud.oscc_cloud|default(item_cloud.name) }}"
    state: "{{ item_router.state|default(omit) }}"
    name: "{{ item_router.name }}"
    network: "{{ item_router.network }}"
    admin_state_up: "{{ item_router.admin_state_up|default(omit) }}"
    enable_snat: "{{ item_router.enable_snat|default(omit) }}"
    external_fixed_ips: "{{ item_router.external_fixed_ips|default(omit) }}"
    interfaces: "{{ item_router.interfaces|default(omit) }}"
