---
- os_image:
    cloud: "{{ item_cloud.oscc_cloud|default(item_cloud.name) }}"
    state: "{{ item_image.state|default(omit) }}"
    name: "{{ item_image.name }}"
    container_format: "{{ item_image.container_format|default(omit) }}"
    disk_format: "{{ item_image.disk_format|default(omit) }}"
    kernel: "{{ item_image.kernel|default(omit) }}"
    ramdisk: "{{ item_image.ramdisk|default(omit) }}"
    filename: "{{ item_image.filename|default(omit) }}"
    min_disk: "{{ item_image.min_disk|default(omit) }}"
    min_ram: "{{ item_image.min_ram|default(omit) }}"
    owner: "{{ item_image.owner|default(omit) }}"
    properties: "{{ item_image.properties|default(omit) }}"
    is_public: "{{ item_image.is_public|default(omit) }}"
    region_name: "{{ item|default(omit) }}"
  with_items: "{{ item_cloud.regions|default(None) }}"
