---
- name: "Processing keypair {{ item_keypair.name }} for {{ item_cloud.oscc_cloud|default(item_cloud.name) }}"
  os_keypair:
    cloud: "{{ item_cloud.oscc_cloud|default(item_cloud.name) }}"
    state: "{{ item_keypair.state|default(omit) }}"
    name: "{{ item_keypair.name }}"
    public_key: "{{ item_keypair.public_key|default(omit) }}"
    public_key_file: "{{ item_keypair.public_key_file|default(omit) }}"
    region_name: "{{ item_cloud.region_name|default(omit) }}"
